//using System;
//using System.Linq;
//using System.Collections.Generic;
//using System.Text;

namespace WS
{
    public enum addressDO : int
    {
        CMD_Start = 0,
        CMD_Stop = 1,
        Status_Run = 2,
        Status_Remote = 3,
        Status_DO1_MSB_Flashing = 4,
        Status_DO2_MSB_Sirene = 5,
        Status_DO3_MSB_PA = 6,
        Status_DO4_MSB = 7,
        Status_DI1_MSB = 8,
        Status_DI2_MSB = 9,
        Status_DI3_MSB = 10,
        Status_DI4_MSB = 11,
        Status_DI5_MSB = 12,
        Status_DI6_MSB = 13,
        Status_DI7_MSB = 14,
        Status_DI8_MSB = 15,
    }

    public enum addressAO : int
    {
        SelectConfig = 0,
        Sequent = 1,
        AccessMode = 2,
        Spare1 = 3,
        Spare2 = 4,
        Spare3 = 5,
        Spare4 = 6,
        Spare5 = 7,
        Spare6 = 8,
        Spare7 = 9,
        Config1_Enable = 10,
        Config2_Enable = 11,
        Config3_Enable = 12,
        Config4_Enable = 13,
        Config5_Enable = 14,
        Config6_Enable = 15,
        Config7_Enable = 16,
        Config8_Enable = 17,
        Config9_Enable = 18,
        Config10_Enable = 19,
        Config1_Durasi_Sirene = 20,
        Config1_Durasi_Delay1 = 21,
        Config1_Durasi_Buzzer1 = 22,
        Config1_Durasi_Delay2 = 23,
        Config1_Durasi_Voice = 24,
        Config1_Durasi_Delay3 = 25,
        Config1_Durasi_Buzzer2 = 26,
        Config1_Durasi_Delay4 = 27,
        Config1_Sirene_Mode = 28,
        Config1_Voice_Index = 29,
        Config2_Durasi_Sirene = 30,
        Config2_Durasi_Delay1 = 31,
        Config2_Durasi_Buzzer1 = 32,
        Config2_Durasi_Delay2 = 33,
        Config2_Durasi_Voice = 34,
        Config2_Durasi_Delay3 = 35,
        Config2_Durasi_Buzzer2 = 36,
        Config2_Durasi_Delay4 = 37,
        Config2_Sirene_Mode = 38,
        Config2_Voice_Index = 39,
        Config3_Durasi_Sirene = 40,
        Config3_Durasi_Delay1 = 41,
        Config3_Durasi_Buzzer1 = 42,
        Config3_Durasi_Delay2 = 43,
        Config3_Durasi_Voice = 44,
        Config3_Durasi_Delay3 = 45,
        Config3_Durasi_Buzzer2 = 46,
        Config3_Durasi_Delay4 = 47,
        Config3_Sirene_Mode = 48,
        Config3_Voice_Index = 49,
        Config4_Durasi_Sirene = 50,
        Config4_Durasi_Delay1 = 51,
        Config4_Durasi_Buzzer1 = 52,
        Config4_Durasi_Delay2 = 53,
        Config4_Durasi_Voice = 54,
        Config4_Durasi_Delay3 = 55,
        Config4_Durasi_Buzzer2 = 56,
        Config4_Durasi_Delay4 = 57,
        Config4_Sirene_Mode = 58,
        Config4_Voice_Index = 59,
        Config5_Durasi_Sirene = 60,
        Config5_Durasi_Delay1 = 61,
        Config5_Durasi_Buzzer1 = 62,
        Config5_Durasi_Delay2 = 63,
        Config5_Durasi_Voice = 64,
        Config5_Durasi_Delay3 = 65,
        Config5_Durasi_Buzzer2 = 66,
        Config5_Durasi_Delay4 = 67,
        Config5_Sirene_Mode = 68,
        Config5_Voice_Index = 69,
        Config6_Durasi_Sirene = 70,
        Config6_Durasi_Delay1 = 71,
        Config6_Durasi_Buzzer1 = 72,
        Config6_Durasi_Delay2 = 73,
        Config6_Durasi_Voice = 74,
        Config6_Durasi_Delay3 = 75,
        Config6_Durasi_Buzzer2 = 76,
        Config6_Durasi_Delay4 = 77,
        Config6_Sirene_Mode = 78,
        Config6_Voice_Index = 79,
        Config7_Durasi_Sirene = 80,
        Config7_Durasi_Delay1 = 81,
        Config7_Durasi_Buzzer1 = 82,
        Config7_Durasi_Delay2 = 83,
        Config7_Durasi_Voice = 84,
        Config7_Durasi_Delay3 = 85,
        Config7_Durasi_Buzzer2 = 86,
        Config7_Durasi_Delay4 = 87,
        Config7_Sirene_Mode = 88,
        Config7_Voice_Index = 89,
        Config8_Durasi_Sirene = 90,
        Config8_Durasi_Delay1 = 91,
        Config8_Durasi_Buzzer1 = 92,
        Config8_Durasi_Delay2 = 93,
        Config8_Durasi_Voice = 94,
        Config8_Durasi_Delay3 = 95,
        Config8_Durasi_Buzzer2 = 96,
        Config8_Durasi_Delay4 = 97,
        Config8_Sirene_Mode = 98,
        Config8_Voice_Index = 99,
        Config9_Durasi_Sirene = 100,
        Config9_Durasi_Delay1 = 101,
        Config9_Durasi_Buzzer1 = 102,
        Config9_Durasi_Delay2 = 103,
        Config9_Durasi_Voice = 104,
        Config9_Durasi_Delay3 = 105,
        Config9_Durasi_Buzzer2 = 106,
        Config9_Durasi_Delay4 = 107,
        Config9_Sirene_Mode = 108,
        Config9_Voice_Index = 109,
        Config10_Durasi_Sirene = 110,
        Config10_Durasi_Delay1 = 111,
        Config10_Durasi_Buzzer1 = 112,
        Config10_Durasi_Delay2 = 113,
        Config10_Durasi_Voice = 114,
        Config10_Durasi_Delay3 = 115,
        Config10_Durasi_Buzzer2 = 116,
        Config10_Durasi_Delay4 = 117,
        Config10_Sirene_Mode = 118,
        Config10_Voice_Index = 119,
    }

    //class Ref
    //{
    //}
}
